import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Icon, LeftArrow, RightArrow } from "../components/Icons";
import { useState } from "react";

export type Emotion = "Smile" | "Anxious" | "Shocked" | "Confused";

const EmotionTypes: Emotion[] = ["Smile", "Anxious", "Shocked", "Confused"];

const Home: NextPage = () => {
  const [state, setState] = useState(0);

  const increase = () => {
    state === Number(EmotionTypes.length - 1)
      ? setState(0)
      : setState((e) => e + 1);
  };

  const decrease = () => {
    state <= 0
      ? setState(Number(EmotionTypes.length - 1))
      : setState((e) => e - 1);
  };

  const link = `http://localhost:3000/api/hello?emo=${EmotionTypes[state]}`;

  return (
    <div className={styles.container}>
      <Head>
        <title>
          How to create Avatar Maker or Avatar Generator with React || Nextjs
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex se center gap-10">
          <button className="btn" onClick={() => decrease()}>
            <LeftArrow />
          </button>
          <Icon emotion={EmotionTypes[state]} />
          <button className="btn" onClick={() => increase()}>
            <RightArrow />
          </button>
        </div>
        <div className="white mt-10">{EmotionTypes[state]}</div>

        <a
          target={"_blank"}
          rel="noreferrer"
          href={link}
          className="blue mt-30"
        >
          Link Preview
        </a>
      </main>
    </div>
  );
};

export default Home;
